version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_SERVICE_URL=http://flask:5000