# Remover "version" se aparecer aviso de obsoleto
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-django
    container_name: django_app
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
    environment:
      - EMAIL_HOST=postfix        # Usa "postfix" (nome do serviço, não container_name)
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_HOST_USER=no-reply@ephor.com.br
      - EMAIL_HOST_PASSWORD=SUASENHA
    networks:
      - app_network
    ports:
      - "8000:8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx_app
    volumes:
      - staticfiles:/usr/share/nginx/html/static
    depends_on:
      - django
    networks:
      - app_network
    ports:
      - "8080:80"

  postfix:
    build:
      context: .
      dockerfile: Dockerfile-postfix
    container_name: postfix  # Nome fixo para o container
    restart: always
    volumes:
      - /opt/opendkim/keys/ephor.com.br:/etc/opendkim/keys/ephor.com.br:ro
      - ./opendkim.conf:/etc/opendkim.conf:ro
      - ./opendkim:/etc/default/opendkim:ro
      - ./postfix-main.cf:/etc/postfix/main.cf:ro
    networks:
      - app_network
    ports:
      - "25:25"
      - "465:465"
      - "587:587"

networks:
  app_network:
    driver: bridge

volumes:
  staticfiles:
