services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-django
    container_name: django_app
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
    environment:
      - EMAIL_HOST=postfix
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_HOST_USER=no-reply@ephor.com.br
      - EMAIL_HOST_PASSWORD=xH3xD7jL6vX5sZ3n
      - DJANGO_SUPERUSER_PASSWORD=zH23yA16cL2yqA76wW622jK5rrsQ
      - DJANGO_SUPERUSER_EMAIL=jhs.importa@gmail.com
      - DJANGO_SETTINGS_MODULE=ephor_2025.settings
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      app_network:
        ipv4_address: 172.18.0.10
    depends_on:
      - postfix
    ports:
      - "8000:8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx_app
    volumes:
      - staticfiles:/usr/share/nginx/html/static:ro
    depends_on:
      - django
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      app_network:
        ipv4_address: 172.18.0.20
    ports:
      - "8080:80"

  postfix:
    build:
      context: .
      dockerfile: Dockerfile-postfix
    container_name: postfix
    restart: always
    volumes:
      - /var/log/mail:/var/log/mail
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      app_network:
        ipv4_address: 172.18.0.30
    ports:
      - "25:25"
      - "465:465"
      - "587:587"

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  staticfiles:
