# Dockerfile-nginx
FROM nginx:latest

# Copiar o arquivo de configuração "default.conf" para a pasta de configs do Nginx
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Diretório padrão para servir estáticos: /usr/share/nginx/html
# (Não copiamos nada aqui, porque usaremos volume no docker-compose)
