# Generated by Django 4.2.18 on 2025-01-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_flaskinstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
