"""
Django settings for ephor_2025 project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Diretório base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# Chave secreta (não usar em produção)
SECRET_KEY = 'django-insecure-man)2xatd%#8fpu*5=m()hy(c$eeqel5qk(=7#n62iz64aer2t'

# Modo debug (não usar em produção)
DEBUG = True

# Hosts permitidos
ALLOWED_HOSTS = ['ephor.com.br', 'localhost', '127.0.0.1', '192.168.0.14', '172.30.0.3']

# Aplicativos instalados
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',  # Para servir arquivos estáticos
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'blog',
]

# Middlewares
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Configuração de URLs
ROOT_URLCONF = 'ephor_2025.urls'

# Configuração de templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Configuração do WSGI
WSGI_APPLICATION = 'ephor_2025.wsgi.application'

# Banco de dados (SQLite por padrão)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Validações de senha
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configurações de localização
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Arquivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Diretório onde os arquivos estáticos serão coletados
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Diretório para arquivos estáticos personalizados
]

# Usar ManifestStaticFilesStorage para evitar conflitos de arquivos duplicados
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# ID de campo padrão para chaves primárias
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Autenticação
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Configuração do site para django-allauth
SITE_ID = 1

# Redirecionamentos de login e logout
LOGIN_REDIRECT_URL = 'instance_list'
ACCOUNT_LOGOUT_REDIRECT_URL = 'landing_page'

CSRF_TRUSTED_ORIGINS = ['https://ephor.com.br',]
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Configuração de envio de e-mails via Postfix no Docker
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'postfix'  # MESMO nome do serviço acima
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'no-reply@ephor.com.br'
EMAIL_HOST_PASSWORD = 'suasenha'
DEFAULT_FROM_EMAIL = 'no-reply@ephor.com.br'
